elasticsearch:
    image: elasticsearch:5.0.1
    restart: on-failure

geth:
    image: ethereum/client-go:alpine
    entrypoint: sh /root/start_geth.sh
    volumes:
       - ./:/root
    restart: on-failure
    ports:
        - '8545:8545'
        - '8546:8546'

augur_node:
    image: augurproject/augur-node:0.3.4
    command: sh /home/augur/start_augur_node.sh
    environment:
        - ELASTIC_HOST=elasticsearch
        - ELASTIC_PORT=9200
        - GETH_HOST=geth
    ports:
        - '8547:8547'
    links:
        - elasticsearch
        - geth
    restart: on-failure
